### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by MikeHibbert** [nerdocs/pydifact#1]
Hi

I'm interested in using this module but it needs a basic HOWTO so its possible to see how to use it.

Mike

**Comment by nerdoc** [comment]
Hi Mike, though I am releasing this as stable some-day™ ;-), it is not ATM.
I have some trouble with the parser as I transcoded it nearly 1:1 from the very good [PHP implementation of metroplex systems](https://github.com/metroplex-systems/edifact).
If you want you can add some code / help out a bit, I think that most parts are quite well.
As said in the README, it's pre-alpha.

I'll write a proper HOWTO, or at least include it in the README - that's a good idea.

**Comment by nerdoc** [comment]
I wrote a really simple usecase in the README. Please tell me what else you need.

**Comment by monkeypants** [comment]
We are evaluating this for a project, if the project goes ahead then we will be happy to contribute time to the features/changes we need. It would be helpful if you documented:
 * any shortcomings in pydifact you are aware of
 * things that you think need more work done to them
 * alternatives in the python ecosystem users might consider

**Comment by monkeypants** [comment]
Thanks! great answer. Would you accept a PR with that in the README?

**Comment by nerdoc** [comment]
Sure! Any PR that helps is welcome!

**Comment by nerdoc** [comment]
Do you need more? Is there anything I can do? Can I close this issue from your side?

**Comment by JocelynDelalande** [comment]
On that documentation topic, what about uploading the sphinx doc on readthedocs.io to improve its visibility, even if it is bare API doc.

**Comment by nerdoc** [comment]
PR Please for your limitations/alternatives ;-)
Yes, I already have a project there. But last time it failed to build, and I had no time yet. Let's see what I can do.

**Comment by nerdoc** [comment]
Ok, it was just a small setting (master_doc). Done.
So the  *No documentation* issue can be closed.
If there is to few documentation for anyone, he/she could open another issue - or help writing it ;-)

**Comment by nerdoc** [comment]
Ah, forgot to link it here: https://pydifact.readthedocs.io
