### ISSUE TITLE
serialize with default characters

### ISSUE THREAD

**Issue by ChristianGerloff** [nerdocs/pydifact#12]
Hey,

unfortunately, b1215db81207b23a836670c79ce085ad09fc9c32 is raising an issue in case of unspecified characters :

# observed behaviour
```
add.segement(Segment("UNA"))
...
```
acess the empty `elements`  list in the `Message` class:
```
self.characters = Characters.from_str(segment.elements[0]
```
# suggestion
```
            if segment.elements:
                self.characters = Characters.from_str(segment.elements[0])
```
I hope that helps :smiley:

**Comment by nerdoc** [comment]
That's a good idea. Thanks.

**Comment by nerdoc** [comment]
Eh, thought about it again.

Why would anyone create a UNA segment without the default characters. That's against the specification.
Sure, you can't so a `add.segements("UNA")` in pydifact. But *there* an exception should be raised maybe. An empty UNA segment simply isn't acceptable - or am I wrong - is there any corner case where this would make sense?

**Comment by nerdoc** [comment]
oh, and `.add_segments("UNA")` isn't a correct usage. the parameter of `add_segments` should be a list of Segments. I made the parameters more clear - but they should already.

**Comment by ChristianGerloff** [comment]
Hey,
yes you are right, the UNA segement is mandatory for the EDImesage. I am adding a UNA segment with add.segment` to a message object. Your `add_segement` function added directly an element containing the default characters so that `add.segement("UNA")` created "UNA:.? '" which was a really gentle solution because the user did not have to specify the already defined characters via add.segement("UNA", ".? '" ) . Nevertheless, with the above-mentioned commit, the same "autocomplete" of the UNA segment is still available, but the function tries to access an empty  element, which results in the error

**Comment by nerdoc** [comment]
I think you are using the API wrongly. `add_segment("UNA")` or `add_segment("UNA", ".? '")` is not possible. You have to call `add_segment(Segment("UNA", ".? '"))`as the parameter must be a Segment, see [here](https://github.com/nerdocs/pydifact/blob/master/pydifact/message.py#L116)

But yes, you can use `add_segment(Segment("UNA"))` without a default character string.
And `add_segment` does not check if the **UNA** segment really has elements. But this has to be enforced by Segment, not by Message, when **creating** a Message. When reading a message using the parser, this could be fault tolerant, like you suggested.

But when **creating** an UNA Segment, doing that without specifying characters MUST be an error.

But maybe yo are right, and this should be done in the Segment class. But this would imply other checks too.

I think I'll use another solution for that. There are other segments which have necessary constraints too, like the UNB Segment, which also has a certain style (first UNOA...UNOF:sender:receiver... etc), envelopes etc.
I wouldn't implement a simple `if elements: read(elements)` check in the Message, this is just not the right place to do this.

The way to go is subclass Segments like

    class UNAElement(Element):
        # do the check here

    ...

    mymessage.add_segments(UNAElement(), 
        HeaderSegment(), 
        BGMSegment(),
        Envelope(
            FooSegment(), 
            FooSegment)
        )
    )

This is far more clear.

**Comment by ChristianGerloff** [comment]
sry @nerdoc  I was just lazy. Sure the input is a `Segment`. Yes, this would be probably a more favourable check. However, a solution without forcing the user to specify the characters (e.g. ".? '")  might be more beneficial because your beautiful repo already provides the user with the default character set.

**Comment by nerdoc** [comment]
Hm, yes - but the Segment() class is a **very** low level class which does not know anything about which kind of segment is meant. It doesn't do any checks and shouldn't.
Why, if checking for the characters, shouldn't it also check for the correctness of a FTX segment, or a QTY segment then?
This really is task of a higher level class, and not of the segment.
Maybe we could implement this "most basic of all checks" at the Message level.

I implemented (in a couple of minutes) the basic prototype of an `UNASegment` class (haven't pushed this change yet) - which is really easy to do. And creating a segment by it's name is much more convenient than using the low level `Segment` class for that directly, as end user.

The library is not really finished ;-)
But give me a few days and I'll push the `UNASegment`, `UNBSegment` and other classes, I just need some tests for them before pushing.

**Comment by nerdoc** [comment]
Additionally, there are syntax changes in between versions. e.g. date fields in v1 are 6 digits, in v3 8 digits. So I have to split the Segment implementation using various versions.
Only the UNA segment is unchanged over time.

**Comment by nerdoc** [comment]
I made a basic `UNASegment` class, you can use that for your purposes now. Please tell me if this does not suit your needs. As I said, don't expect the low level `Segment` class to do checks - it would be less performant (these checks would run in EVERY segment creation, not just in the UNA segment). So better is separating the segments.

Beware. the syntax I implemented is only for v1 - currently mainly v3 or v4 are used. Not here - to scratch my own itch I began with v1 - but the UNA segment is the same.
