### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by werkshy** [nerdocs/pydifact#15]
I know pydifact is described as unstable, but a PyPI release would make it easier to adopt and might drive some contributors. As far as I can tell, it's not currently available.

**Comment by JocelynDelalande** [comment]
I second this comment : I almost missed this because it was absent from pypi.

**Comment by nerdoc** [comment]
I'll do that ASAP, promised.

**Comment by nerdoc** [comment]
Done.
https://pypi.org/project/pydifact/
Please have a look at it, PRs and improvements very welcome.

**Comment by JocelynDelalande** [comment]
Cheers, thanks for that :-).

One thing I don't get is why the description « A Python EDI file parser. » does not appear on Pypi even if it is filled in setup.cfg. On the other hand, the classifiers have been extracted correctly and displayed on Pypi.

Anyone has an idea ?

**Comment by nerdoc** [comment]
Yes. "description" should better be named "short-description". It IS displayed...
You mean "long_description", I added a link to README.md - this is now displayed, and made a new release (thanks to my shiny new publish bash script for pypi packages done in 1 Minute... ;-) )
