### ISSUE TITLE
Does PIP Install and git clone PYDIFACT do the same thing ?

### ISSUE THREAD

**Issue by srinirokz** [nerdocs/pydifact#25]
I am planning to generate EDIFACT file using PYDIFACT. As suggested in the usage am using PIP install, but i am unable to import pydifact.segmentcollection to generate a EDIFACT file.
Please advise
![image](https://user-images.githubusercontent.com/44640709/91013112-8e61a400-e62a-11ea-8947-cd1893cdf4f1.png)

**Comment by nerdoc** [comment]
No. like the [README](https://github.com/nerdocs/pydifact) says:

    However, it is not stable yet, so the pypi version, including documentation an code examples, 
    could differ from the latest git code. If in doubt, use the git version

**Comment by srinirokz** [comment]
Thank you
