### ISSUE TITLE
Remove old Python(3.5) compatibility

### ISSUE THREAD

**Issue by nerdoc** [nerdocs/pydifact#36]
All format strings could be changed into f-Strings - but due to @theangryangel's requirements in a project (see [PR](https://github.com/nerdocs/pydifact/pull/35)), compatibility to Python 3.5 will be maintained until this project is upgraded.

This issue can be closed after his requirement is upgraded.
BTW @theangryangel - what would be nice: a git pre-commit hook that checks compatibility with Python 3.5... or a CI with a Python 3.5 environment... Just if you find time.

**Comment by FelixSchwarz** [comment]
How about just adding Python 3.5 to your `.travis.yml`? I think travis still provides Python 3.5.

**Comment by nerdoc** [comment]
Sure. @JocelynDelalande, anything against that? You're the one who uses CI most. If you don't mind I'll add 3.5, until @theangryangel gets rid of it?

**Comment by JocelynDelalande** [comment]
No prob :)

**Comment by nerdoc** [comment]
Done with 82b6c601997da145f5d2bedc337642b95e6817d3
