### ISSUE TITLE
New release with changes?

### ISSUE THREAD

**Issue by raguiar2** [nerdocs/pydifact#39]
It seems that a lot of changes have been introduced in pydifact since the last release on pypi. Are there plans for a new 1.0 release any time soon?

**Comment by nerdoc** [comment]
definitely not 1.0. The changes are all WIP, have a close watch on #18 to see the progress there. @theangryangel does the main work in that Issue, and I ATM have a 70+ hours week in my day job (as MD).
1.0 should be stable, usable, tested. There are many fields where this is not the case - only the low-level API does work very well IMHO - everything above is, as said, WIP ATM. Doens't mean that it's not usable.
What would be a big help is to draft the high level API further, we we can make it happen.

But anyway, the low-level API is pretty stable and won't change much any more.
's that OK for you?

**Comment by FelixSchwarz** [comment]
What about a 0.0.6 release? A new pypi release would trigger some notification on our side (and would probably mean we try the new version with our current code). Releasing regularly means that we don't have to do too much catch-up at once (and we could provide input if a new release breaks our use case).

**Comment by nerdoc** [comment]
Yes, 0.0.6 is definitely the way to go, good idea. I'll do that. Is that OK for all to close this issue after that?

**Comment by raguiar2** [comment]
Sure, 0.0.6 makes sense to me

**Comment by nerdoc** [comment]
Ok, new version 0.0.6 is available on pypi, please test as you wish ;-)
I am working on small changes to add line numbers to the game, expect to have that soon(TM). See #26

**Comment by FelixSchwarz** [comment]
Thank you. I just noticed that we used a pre-release version from August or so already as we need some of the changes :-)
Anyway, all of our tests still pass with new version. Looking forward to the high-level API so we can replace even more of our home-grown code.
