### ISSUE TITLE
Issue on UNZ segment

### ISSUE THREAD

**Issue by Selkis78** [nerdocs/pydifact#42]
Hello
I've recently reinstall pydifact with PyPI.
My programm load a file, do some changes in data and serialize.

All was working with version pydifact-0.0.5. Edifact is parsed ok by my banking software.
But with the last version, when i load an existing edifact file with from_file() and then serialize, my bank software reports error during controls.

UNZ in the original file is : 'UNZ+1+XXXDVINT'
In the serialized file, the function get_footer_segment changes the value by : 'UNZ+17+XXXDVINT'
I not sure (i am not an edifact expert...) but second value should be 1 and not 17.
Maybe the function should only count UNH segment ?

Thanks

**Comment by nerdoc** [comment]
I'll have a look at this. Should not happen.

**Comment by nerdoc** [comment]
According to [here(EDIFACT tutorial, PDF)](https://www.gxs.co.uk/wp-content/uploads/tutorial_edifact.pdf), page 15, you can see that `functional groups` are meant to be `UNG/UNE`envelopes. And **these** are counted in UNZ, if not segments.
So i thought first this is the case.

However, all my EDIFACT files I get in real-lif (and these are many) have no `UNG/UNE` envelopes, and one `UNB/UNZ` message. So you may be right, and the documentation is a bit misleading here...?

This is definitely not correct, as `+2` does not apply to *UNZ*, only to * UNT*, see #44.
```python
if cnt == 0:
        cnt = len(self.segments)+2
```

I'll try to fix that ASAP.
