### ISSUE TITLE
UNT element correctly implemented?

### ISSUE THREAD

**Issue by julian-r** [nerdocs/pydifact#44]
It seems like the `UNT` element outputs the wrong order  here:

https://www.truugo.com/edifact/d96a/unt/

The lib outputs:
`UNT+1+272'` 

For a message with 273 elements. Actually it should be:
`UNT+273+1'`

Am I wrong? Is D96A a different standard?

**Comment by nerdoc** [comment]
Hmmmm. yes. TBH, Segments in production should not use `Segment`directly. The docstring says: 

    This class is used internally. read-world implementations of specialized should subclass 
    Segment and provide the `tag` and `validate` attributes.

That's my (our, pydifact's) job in the end, I know.

I plan to have a segment like `UNTSegment(..., ..., ...)` as **subclsas** of `Segment`. But let's see what I can do here...

**Comment by nerdoc** [comment]
Ah, sorry, I saw (after formatting) that you use `Message` correctly...

**Comment by nerdoc** [comment]
Thanks @fabriziogozzi - this was the right hint. I had to fix a bunch of tests too, as we (me and @JocelynDelalande) repeated this error even into the tests. So pydifact always had clean test results with bad test data... ;-)

Thanks to all! I'll provide a new hotfix version later today.

**Comment by JocelynDelalande** [comment]
Thanks to you two :)
