### ISSUE TITLE
Is pydifact stable yet?

### ISSUE THREAD

**Issue by crooksey** [nerdocs/pydifact#7]
Hi Christian,

Is this library 'stable' yet? If not, what are the current limitations?

**Comment by nerdoc** [comment]
No, it's a WIP. Although I couldn't find any errors as long as I tested it (and I am currently changing the test framework from unittest to pytest), it lacks of higher level features and just is able to "read" a EDIFACT file. What needs to be done is e.g. reading Envelopes.

I will definitely use this library i my own software on the long run, so it won't go away soon. But I don't have much time ATM to make a fast-paced development.
