### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by nerdoc** [nerdocs/pydifact#8]
I decided to change the license from LGPL to a more "permissive" one like MIT. The "original" license of the php pendant is Apache 2.0 license.
A user asked me if he can use it in a commercial project. MIT helps to spread it more. People that are willing to give something back by creating a PR do that anyways. People who use software illegally do it anyways, even if restrictive, proprietary licenses forbid that.

With this change I hope more people can use this software.

**Comment by nerdoc** [comment]
@mohan3d and @bloodywing, are you ok with that - you have (small, but important) changes in this software

**Comment by mohan3d** [comment]
I would be happy with this.

**Comment by bloodywing** [comment]
Sure, no problem for me.

**Comment by nerdoc** [comment]
Thanks, done.

**Comment by nerdoc** [comment]
Exactly, I had done this  5 days before - and would have reverted it if anyone had a complain. Sorry to have been a bit fast... ;-)
https://github.com/nerdocs/pydifact/commit/8dd72dbb3edd76e9472bcb11839924946af0ba6c
